### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by brotherlogic** [brotherlogic/recordgetter#14]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x3c pc=0x13fec]

goroutine 1 [running]:
panic(0x3fc690, 0x1080a038)
	/usr/local/go/src/runtime/panic.go:481 +0x330
main.scoreCard(0x4e9c4e, 0x4, 0x10810550, 0x9, 0x109342a0, 0x5, 0x0)
	/home/simon/code/src/github.com/brotherlogic/recordgetter/recordget.go:146 +0x2a4
main.processCard(0x4705e8, 0x9, 0xc387, 0x498f00, 0x0)
	/home/simon/code/src/github.com/brotherlogic/recordgetter/recordget.go:211 +0x51c
main.main()
	/home/simon/code/src/github.com/brotherlogic/recordgetter/recordget.go:250 +0x120

**Comment by brotherlogic** [comment]
WAI
