### ISSUE TITLE
Fix weird conversion error

### ISSUE THREAD

**Issue by brotherlogic** [brotherlogic/recordgetter#15]
panic: invalid argument to Intn

goroutine 1 [running]:
panic(0x393318, 0x10864888)
	/usr/local/go/src/runtime/panic.go:481 +0x330
math/rand.(*Rand).Intn(0x108640e0, 0x0, 0x10915130)
	/usr/local/go/src/math/rand/rand.go:98 +0x6c
math/rand.Intn(0x0, 0x74ac47f8)
	/usr/local/go/src/math/rand/rand.go:213 +0x2c
main.getReleaseFromCollection(0x109ee100, 0x9, 0x10914ff8, 0x5, 0x10914d01, 0x0, 0x0)
	/home/simon/code/src/github.com/brotherlogic/recordgetter/recordget.go:93 +0x10f0
main.main()
	/home/simon/code/src/github.com/brotherlogic/recordgetter/recordget.go:267 +0x790

**Comment by brotherlogic** [comment]
This was a result of discogs being empty
